version: "3.4"

services:
  mq.receiver:
    image: ${DOCKER_REGISTRY-}mqreceiver
    build:
      context: .
      dockerfile: MQ.Receiver/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - default

  mq.sender:
    image: ${DOCKER_REGISTRY-}mqsender
    build:
      context: .
      dockerfile: MQ.Sender/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - default

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    name: mq_net
