version: "3.4"

services:
  mq.receiver:
    image: ${DOCKER_REGISTRY-}mqreceiver
    build:
      context: .
      dockerfile: MQ.Receiver/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  mq.sender:
    image: ${DOCKER_REGISTRY-}mqsender
    build:
      context: .
      dockerfile: MQ.Sender/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  rabbitmq:
    container_name: rabbitmq
    hostname: ex-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:latest
    volumes:
        - .docker/rabbitmq/data/:/var/lib/rabbitmq/
        - .docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge