version: "3.4"

services:
  mq.receiver:
    image: ${DOCKER_REGISTRY-}mqreceiver
    build:
      context: .
      dockerfile: MQ.Receiver/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbit_network

  mq.sender:
    image: ${DOCKER_REGISTRY-}mqsender
    build:
      context: .
      dockerfile: MQ.Sender/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbit_network

  rabbitmq:
    container_name: rabbitmq
    hostname: ex-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:latest
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"
    networks:
      - rabbit_network

networks:
  rabbit_network:
    driver: bridge
    name: mq_net
